# Generated by Django 3.2.5 on 2021-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url_picture', models.TextField(verbose_name='url картинки')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания поста')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обнавления')),
                ('counter_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('readers', models.IntegerField(default=0, verbose_name='Количество читателей')),
            ],
        ),
    ]
