# Generated by Django 3.2.5 on 2021-07-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210726_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-counter_views'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Book_book_status', to='index.bookstatus'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания поста'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обнавления'),
        ),
    ]
