# Generated by Django 3.2.5 on 2021-07-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210726_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['counter_views'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
