# Generated by Django 3.2.5 on 2021-07-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210726_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
