# Generated by Django 3.2.5 on 2021-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_bookstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Статус'),
        ),
    ]
