# Generated by Django 3.2.5 on 2021-07-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_bookstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Book_book_status', to='index.bookstatus', verbose_name='Статус книги'),
        ),
    ]
