# Generated by Django 3.2.5 on 2021-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('genre', models.TextField(blank=True, null=True, verbose_name='Жанр')),
                ('language', models.TextField(verbose_name='Язык')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'Authors',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='AuthorsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'AuthorsStatus',
                'ordering': ['name'],
            },
        ),
    ]
