# Generated by Django 3.2.5 on 2021-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsstatus',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='authors',
            name='birthday',
            field=models.DateTimeField(db_index=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
