# Generated by Django 3.2.5 on 2021-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_author', '0002_auto_20210730_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='style',
            field=models.CharField(choices=[('anc Greek', 'Ancient Greek Literatura'), ('anc Roma', 'Ancient Roma Literatura'), ('anc Belarus', 'Ancient Belarus Literatura')], default='anc Belarus', max_length=20, verbose_name='Стиль литературы'),
        ),
    ]
