# Generated by Django 3.2.5 on 2021-08-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_author', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
